services:
  web:
    build: .
    container_name: simple_lms_web
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: simple_lms.settings

  db:
    image: postgres:15   # <- gunakan versi 15 agar cocok dengan Django
    container_name: simple_lms_db
    environment:
      POSTGRES_DB: simple_lms_db
      POSTGRES_USER: simple_lms_user
      POSTGRES_PASSWORD: simple_lms_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
